//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllFBStatu
    {
        public int FBStatusID { get; set; }
        public string FBStatus { get; set; }
        public Nullable<short> Active { get; set; }
        public Nullable<short> StatusSequence { get; set; }
        public string StatusFor { get; set; }
        public Nullable<int> SolutionID { get; set; }
        public string Email { get; set; }
    }
}
