//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCInvoiceDetail
    {
        public int Id { get; set; }
        public Nullable<int> WorkorderId { get; set; }
        public Nullable<decimal> TravelCost { get; set; }
        public Nullable<decimal> LaborCost { get; set; }
        public Nullable<decimal> PartsCost { get; set; }
        public Nullable<decimal> PartsDiscount { get; set; }
        public Nullable<double> SalesTax { get; set; }
        public string TransactionId { get; set; }
        public Nullable<bool> ManualCosts { get; set; }
    
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
