//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contingent
    {
        public int ContingentID { get; set; }
        public string ContingentName { get; set; }
        public string ContingentType { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
