//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipType
    {
        public string EquipTypeCode { get; set; }
        public string Description { get; set; }
        public int EquipTypeId { get; set; }
        public Nullable<int> Sequence { get; set; }
    }
}
