//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class Erf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Erf()
        {
            this.FBERFEquipments = new HashSet<FBERFEquipment>();
            this.FBERFExpendables = new HashSet<FBERFExpendable>();
        }
    
        public string ErfID { get; set; }
        public Nullable<int> WorkorderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerState { get; set; }
        public string CustomerZipCode { get; set; }
        public string CustomerMainContactName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerPhoneExtn { get; set; }
        public string CustomerMainEmail { get; set; }
        public Nullable<int> FeastMovementID { get; set; }
        public Nullable<short> ChannelID { get; set; }
        public string SalesPerson { get; set; }
        public Nullable<int> EntryUserID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> ModifiedUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<short> ReasonID { get; set; }
        public Nullable<System.DateTime> DateOnERF { get; set; }
        public Nullable<System.DateTime> DateERFReceived { get; set; }
        public Nullable<System.DateTime> DateERFProcessed { get; set; }
        public Nullable<System.DateTime> TimeERFProcessed { get; set; }
        public Nullable<System.DateTime> OriginalRequestedDate { get; set; }
        public string InstallLocation { get; set; }
        public Nullable<int> TimeZone { get; set; }
        public string DayLightSaving { get; set; }
        public Nullable<System.DateTime> EquipETADate { get; set; }
        public Nullable<int> ShipToJDE { get; set; }
        public string SiteReady { get; set; }
        public Nullable<System.DateTime> JdeProcessDate { get; set; }
        public Nullable<int> ShipfromJDE { get; set; }
        public string UserName { get; set; }
        public string TransType { get; set; }
        public string CustomerPO { get; set; }
        public string CmUser { get; set; }
        public Nullable<System.DateTime> CmReceviedDate { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public string LoanSale { get; set; }
        public string HoursofOperation { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> IsSiteReady { get; set; }
        public string OrderType { get; set; }
        public string ShipToBranch { get; set; }
        public string ERFStatus { get; set; }
        public Nullable<decimal> TotalNSV { get; set; }
        public Nullable<decimal> CurrentEqp { get; set; }
        public Nullable<decimal> AdditionalEqp { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<decimal> CurrentNSV { get; set; }
        public string ContributionMargin { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string BulkUploadResult { get; set; }
        public string UploadError { get; set; }
        public string CashSaleStatus { get; set; }
        public string Tracking { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FBERFEquipment> FBERFEquipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FBERFExpendable> FBERFExpendables { get; set; }
    }
}
