//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESMCCMRSMEscalation
    {
        public int ID { get; set; }
        public string ZIPCode { get; set; }
        public string Country { get; set; }
        public Nullable<double> EDSMID { get; set; }
        public string ESMName { get; set; }
        public string ESMPhone { get; set; }
        public string ESMEmail { get; set; }
        public Nullable<double> CCMID { get; set; }
        public string CCMName { get; set; }
        public string CCMEmail { get; set; }
        public string CCMPhone { get; set; }
        public Nullable<double> RSMID { get; set; }
        public string RSM { get; set; }
        public string RSMEmail { get; set; }
        public string RSMPhone { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
