//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESMDSMRSM
    {
        public int ID { get; set; }
        public string Region { get; set; }
        public string RegionName { get; set; }
        public Nullable<int> RSMID { get; set; }
        public string RSM { get; set; }
        public string RSMEmail { get; set; }
        public string RSMPhone { get; set; }
        public string BranchNO { get; set; }
        public string Branch { get; set; }
        public Nullable<int> EDSMID { get; set; }
        public string ESMName { get; set; }
        public string ESMPhone { get; set; }
        public string ESMEmail { get; set; }
        public Nullable<int> CCMID { get; set; }
        public string CCMName { get; set; }
        public string CCMEmail { get; set; }
        public string CCMPhone { get; set; }
    }
}
