//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBCBE
    {
        public int Id { get; set; }
        public string ItemNumber { get; set; }
        public string ItemDescription { get; set; }
        public string SerialNumber { get; set; }
        public string AssetStatus { get; set; }
        public string CurrentLocation { get; set; }
        public Nullable<int> CurrentCustomerId { get; set; }
        public string CurrentCustomerName { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<decimal> InitialValue { get; set; }
        public Nullable<System.DateTime> InitialDate { get; set; }
        public string CurrentGLCode { get; set; }
        public string CurrentGLObject { get; set; }
    }
}
