//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBCustomerServiceDistribution
    {
        public int ServiceId { get; set; }
        public string Route { get; set; }
        public string Branch { get; set; }
        public string RSRName { get; set; }
        public string RSRPhone { get; set; }
        public string RSREmail { get; set; }
        public string SalesManagerName { get; set; }
        public string SalesManagerPhone { get; set; }
        public string SalesMmanagerEmail { get; set; }
        public string RegionalsName { get; set; }
        public string RegonalsPhone { get; set; }
        public string RegionalsEmail { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
