//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBEquipment
    {
        public int ProductId { get; set; }
        public string ProdNo { get; set; }
        public string ModelNO { get; set; }
        public string Description { get; set; }
        public string UnitPrice { get; set; }
    }
}
