//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBFunctionality
    {
        public int FunctionID { get; set; }
        public Nullable<int> ParentFunctionID { get; set; }
        public string FunctionName { get; set; }
        public Nullable<int> FunctionLevel { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Order { get; set; }
    }
}
