//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBSKU
    {
        public int SKUId { get; set; }
        public string SKU { get; set; }
        public string Description { get; set; }
        public Nullable<bool> SKUActive { get; set; }
        public string Weight { get; set; }
        public string SKUCost { get; set; }
        public string VendorCode { get; set; }
        public string ShortProductNumber { get; set; }
        public string SystemSource { get; set; }
        public string Ben02ItemNumber { get; set; }
        public string VendorNo { get; set; }
        public string E1Number { get; set; }
    }
}
