//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBUserReport
    {
        public int UserReportId { get; set; }
        public int UserId { get; set; }
        public int report_id { get; set; }
    
        public virtual FBReport FBReport { get; set; }
        public virtual FbUserMaster FbUserMaster { get; set; }
    }
}
