//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class FbWorkOrderSKU
    {
        public int WorkOrderSKUId { get; set; }
        public int WorkorderID { get; set; }
        public string SKU { get; set; }
        public Nullable<int> Qty { get; set; }
    }
}
