//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceUniqueid { get; set; }
        public string Invoiceid { get; set; }
        public Nullable<int> WorkorderID { get; set; }
        public string CustomerName { get; set; }
        public string ServiceLocation { get; set; }
        public Nullable<System.DateTime> WorkorderCompletionDate { get; set; }
        public string InvoiceStatus { get; set; }
        public Nullable<System.DateTime> InvoiceSubmitDate { get; set; }
        public Nullable<decimal> SubmitAmount { get; set; }
        public Nullable<System.DateTime> PaymentCreated { get; set; }
        public Nullable<decimal> PaymentAmtApproved { get; set; }
        public string CheckNumber { get; set; }
        public Nullable<int> Mileage { get; set; }
        public Nullable<int> TravelTimeInSecs { get; set; }
        public Nullable<int> StandardTravelSecs { get; set; }
        public Nullable<int> OverTimeTravelSecs { get; set; }
        public Nullable<short> RoundTripIncluded { get; set; }
        public Nullable<decimal> LaborHours { get; set; }
        public Nullable<decimal> StandardLabor { get; set; }
        public Nullable<decimal> OvertimeLabor { get; set; }
        public Nullable<int> ZoneRateid { get; set; }
        public Nullable<decimal> AdditionalCharge { get; set; }
        public string AdditionalChargeDescription { get; set; }
        public string InvoiceComments { get; set; }
        public Nullable<decimal> PartsTotal { get; set; }
        public Nullable<decimal> LaborTotal { get; set; }
        public Nullable<decimal> TravelTotal { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> InvoiceTotal { get; set; }
        public Nullable<decimal> PhoneSolveTotal { get; set; }
        public Nullable<decimal> ProjectTotal { get; set; }
        public string OverTimeRequestApproved { get; set; }
        public Nullable<System.DateTime> DateCheckCreated { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> AdjustmentAmount { get; set; }
        public string ApprovedBy { get; set; }
    }
}
