//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class NARF_TradeReference
    {
        public int TradeRefID { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public string CompanyName { get; set; }
        public string AccountId { get; set; }
        public string Phone { get; set; }
        public int CreatedUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedUserID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual NARF_NewAccount NARF_NewAccount { get; set; }
    }
}
