//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotesHistory
    {
        public string ErfID { get; set; }
        public Nullable<int> WorkorderID { get; set; }
        public Nullable<int> FeastMovementID { get; set; }
        public Nullable<int> Userid { get; set; }
        public string UserName { get; set; }
        public string Notes { get; set; }
        public Nullable<short> AutomaticNotes { get; set; }
        public int NotesID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> NonServiceWorkorderID { get; set; }
        public Nullable<short> isDispatchNotes { get; set; }
    
        public virtual NonServiceworkorder NonServiceworkorder { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
