//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemovalSurvey
    {
        public int RemovalSurveyID { get; set; }
        public Nullable<int> WorkorderID { get; set; }
        public Nullable<int> JMSOwnedMachines { get; set; }
        public Nullable<System.DateTime> RemovalDate { get; set; }
        public string RemoveAllMachines { get; set; }
        public string RemovalReason { get; set; }
        public string BeveragesSupplier { get; set; }
    }
}
