//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sku
    {
        public int Skuid { get; set; }
        public string Sku1 { get; set; }
        public string Description { get; set; }
        public Nullable<short> SkuActive { get; set; }
        public string VendorCode { get; set; }
        public Nullable<decimal> SKUCost { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<short> ColUpdated { get; set; }
        public string Manufacturer { get; set; }
        public string JMS_ITEM_NUMBER { get; set; }
        public string VEND_ITEM_NUMBER { get; set; }
        public string EQUIPMENT_TAG { get; set; }
        public string Category { get; set; }
    }
}
