//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class TECH_HIERARCHY_BACKUP
    {
        public int DealerId { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string Contact { get; set; }
        public string SearchType { get; set; }
        public string SearchDesc { get; set; }
        public string DealerType { get; set; }
        public string AreaCode { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string Fax { get; set; }
        public string NextelPhone { get; set; }
        public Nullable<int> SerialNoMan { get; set; }
        public string ServiceRegion { get; set; }
        public string EmailCC { get; set; }
        public string LongAddressNumber { get; set; }
        public string BusinessUnit { get; set; }
        public string RimEmail { get; set; }
        public Nullable<int> BranchAssociations { get; set; }
        public Nullable<System.DateTime> LastModifiedByFTP { get; set; }
        public Nullable<int> SendFax { get; set; }
        public Nullable<int> SendNextel { get; set; }
        public Nullable<int> SendEmail { get; set; }
        public string FamilyAff { get; set; }
        public string FamilyAffDesc { get; set; }
        public Nullable<int> PricingParentId { get; set; }
        public string PricingParentName { get; set; }
        public Nullable<int> SendAutomaticEmail { get; set; }
        public Nullable<int> SendDispatchConf { get; set; }
        public Nullable<int> SendNSREmail { get; set; }
        public string AlternativePhone { get; set; }
        public Nullable<int> AfterHoursOnly { get; set; }
        public Nullable<int> PickFromZipRateTable { get; set; }
        public string CustomerOwnNumber { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUserID { get; set; }
        public string BranchType { get; set; }
        public Nullable<short> Unavailable { get; set; }
        public Nullable<System.DateTime> UnavailableStartDate { get; set; }
        public Nullable<System.DateTime> UnavailableEnddate { get; set; }
        public Nullable<int> ReplacementTech { get; set; }
        public string BranchNumber { get; set; }
        public string BranchName { get; set; }
        public int AutoDispatch { get; set; }
        public string RegionName { get; set; }
        public string FieldServiceManager { get; set; }
        public string RegionNumber { get; set; }
        public Nullable<int> PrimaryTechId { get; set; }
    }
}
