//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThirdpartyConMaintenanceZonerate
    {
        public Nullable<int> ContractMaintenanceid { get; set; }
        public Nullable<int> Techid { get; set; }
        public int ZoneRateid { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string BasedOn { get; set; }
    }
}
