//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_SerialNOReport
    {
        public int EventID { get; set; }
        public string FulfillmentStatus { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public int ContactID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> CallTypeId { get; set; }
        public string CallTypeDesc { get; set; }
        public string SerialNo { get; set; }
        public string ProductNo { get; set; }
        public string ProductDesc1 { get; set; }
        public string Manufacturer { get; set; }
        public string ManufacturerDesc { get; set; }
        public Nullable<int> NoService { get; set; }
        public string SearchType { get; set; }
        public string SearchDesc { get; set; }
    }
}
