//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpinvTransferNonserialized
    {
        public int Transferid { get; set; }
        public Nullable<int> Catalogid { get; set; }
        public string ManufNumber { get; set; }
        public string Description { get; set; }
        public Nullable<int> QtyTransfered { get; set; }
        public string Bin { get; set; }
        public Nullable<int> TechID { get; set; }
        public Nullable<int> Van { get; set; }
    }
}
