//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpinvTransferSerialized
    {
        public int Transferid { get; set; }
        public Nullable<int> Catalogid { get; set; }
        public Nullable<int> WorkorderID { get; set; }
        public Nullable<bool> Sealed { get; set; }
        public string EquipmentStatus { get; set; }
        public string Model { get; set; }
        public string SerialNumber { get; set; }
        public string Manufacturer { get; set; }
        public string FileName { get; set; }
        public string Bin { get; set; }
        public Nullable<int> TechID { get; set; }
        public Nullable<int> Van { get; set; }
    }
}
