//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_EquipmentCount
    {
        public Nullable<int> EquipCount { get; set; }
        public int DealerId { get; set; }
        public string CompanyName { get; set; }
        public string BranchNumber { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> WorkorderCalltypeid { get; set; }
        public string WorkorderCalltypeDesc { get; set; }
        public Nullable<bool> NoServiceRequired { get; set; }
        public Nullable<System.DateTime> WorkorderCloseDate { get; set; }
    }
}
