//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LastOneyearDispatches
    {
        public int WorkorderID { get; set; }
        public string WorkorderCallstatus { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public int DealerId { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> WorkorderEntryDate { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> ScheduleUserid { get; set; }
    }
}
