//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkorderInstallationSurvey
    {
        public int Installsurveyid { get; set; }
        public string NemwNumber { get; set; }
        public string ElectricalPhase { get; set; }
        public string MachineAmperage { get; set; }
        public string UnitFitSpace { get; set; }
        public string Voltage { get; set; }
        public string CounterUnitSpace { get; set; }
        public string WaterLine { get; set; }
        public string AssetLocation { get; set; }
        public string Comments { get; set; }
        public Nullable<int> WorkorderID { get; set; }
        public Nullable<int> AssetID { get; set; }
    
        public virtual WorkOrder WorkOrder { get; set; }
        public virtual WorkorderEquipment WorkorderEquipment { get; set; }
    }
}
