//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkorderSavedSearch
    {
        public string SavedSearchName { get; set; }
        public Nullable<int> Customerid { get; set; }
        public Nullable<int> Erfid { get; set; }
        public Nullable<int> WorkorderID { get; set; }
        public string WorkorderCallStatus { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> FollowupCall { get; set; }
        public string AutoDispatch { get; set; }
        public string WorkorderType { get; set; }
        public string Priority { get; set; }
        public Nullable<int> Fsr { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> CoverageZoneIndex { get; set; }
        public Nullable<int> Tsm { get; set; }
        public string TechType { get; set; }
        public string ServiceCompany { get; set; }
        public string Technician { get; set; }
        public Nullable<int> Techid { get; set; }
        public Nullable<int> Fsm { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<System.DateTime> ApptdateFrom { get; set; }
        public Nullable<System.DateTime> ApptDateTo { get; set; }
        public int SavedSearchid { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> OriginalWorkOrderID { get; set; }
    }
}
