//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkorderSchedule
    {
        public int Scheduleid { get; set; }
        public Nullable<int> WorkorderID { get; set; }
        public Nullable<int> Techid { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<int> ScheduleUserid { get; set; }
        public Nullable<System.DateTime> ModifiedScheduleDate { get; set; }
        public Nullable<int> ModifiedScheduleUserid { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> ServiceCenterID { get; set; }
        public Nullable<short> PrimaryTech { get; set; }
        public string TechName { get; set; }
        public string TechPhone { get; set; }
        public string ServiceCenterName { get; set; }
        public Nullable<int> FSMID { get; set; }
        public string FSMName { get; set; }
        public string FSMPhone { get; set; }
        public Nullable<int> TSMID { get; set; }
        public string TSMName { get; set; }
        public string TSMEmail { get; set; }
        public string TSMPhone { get; set; }
        public string FSMEmail { get; set; }
        public Nullable<int> TeamLeadID { get; set; }
        public string TeamLeadName { get; set; }
        public string AssignedStatus { get; set; }
        public Nullable<short> AssistTech { get; set; }
        public Nullable<System.DateTime> WS_ArrivalDateTime { get; set; }
        public Nullable<System.DateTime> WS_CompletionDateTime { get; set; }
        public Nullable<decimal> WS_Mileage { get; set; }
        public string WS_TravelTime { get; set; }
        public Nullable<System.DateTime> WS_AppointmentDate { get; set; }
        public Nullable<bool> IsTechClosed { get; set; }
        public Nullable<System.DateTime> EventScheduleDate { get; set; }
        public string ScheduleContactName { get; set; }
    
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
