//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkorderServiceClaim
    {
        public Nullable<int> WorkorderID { get; set; }
        public Nullable<int> Assetid { get; set; }
        public Nullable<int> Techid { get; set; }
        public int ServiceClaimid { get; set; }
    
        public virtual WorkorderEquipment WorkorderEquipment { get; set; }
    }
}
