//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkorderReasonlog
    {
        public Nullable<int> WorkorderID { get; set; }
        public Nullable<System.DateTime> OldAppointmentDate { get; set; }
        public Nullable<System.DateTime> NewAppointmentDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> Techid { get; set; }
        public Nullable<int> Reasonid { get; set; }
        public string LogDescription { get; set; }
        public string Notes { get; set; }
        public int WorkorderLogid { get; set; }
        public string ReasonFor { get; set; }
    
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
