//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class YHContact_PMUploadsALL
    {
        public int UniqueID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string CustomerName { get; set; }
        public string Description { get; set; }
        public string EquipmentModel { get; set; }
        public string EquipmentLocation { get; set; }
        public string TPSP { get; set; }
        public Nullable<int> TechID { get; set; }
        public string ContactName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> TimeZone { get; set; }
        public string DayLightSaving { get; set; }
        public string ZipCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string IntervalType { get; set; }
        public Nullable<System.DateTime> NextRunDate { get; set; }
        public Nullable<short> FirstRun { get; set; }
        public Nullable<int> IntervalDuration { get; set; }
        public Nullable<short> EventCreated { get; set; }
        public string Notes { get; set; }
        public string TechName { get; set; }
        public Nullable<short> SpecialUpdate { get; set; }
        public Nullable<short> SkipDate { get; set; }
    }
}
