//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class YHCompassSurvey
    {
        public int EventID { get; set; }
        public int AssetKey { get; set; }
        public Nullable<int> NemaNumberID { get; set; }
        public Nullable<int> AMPSID { get; set; }
        public Nullable<int> VoltageID { get; set; }
        public Nullable<int> WaterLineID { get; set; }
        public Nullable<int> ElectricalPhaseID { get; set; }
        public Nullable<int> UnitSpaceID { get; set; }
        public Nullable<int> UnitWeightID { get; set; }
        public int CompassSurveyID { get; set; }
        public Nullable<int> Removed { get; set; }
        public string SurveyLocation { get; set; }
        public string NemwNumber { get; set; }
        public string ElectricalPhase { get; set; }
        public string MachineAmperage { get; set; }
        public string UnitFitSpace { get; set; }
        public string Voltage { get; set; }
        public string CounterUnitSpace { get; set; }
        public string WaterLine { get; set; }
        public string AssetLocation { get; set; }
    }
}
