//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class YHContact
    {
        public int ContactID { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> DealerId { get; set; }
        public string Phone { get; set; }
        public string SalesRegion { get; set; }
        public string RegionDesc { get; set; }
        public string Division { get; set; }
        public string DivisionDesc { get; set; }
        public string District { get; set; }
        public string DistrictDesc { get; set; }
        public string FamilyAff { get; set; }
        public string FamilyAffDesc { get; set; }
        public string PricingParent { get; set; }
        public string PricingParentName { get; set; }
        public string AcctRep { get; set; }
        public string AcctRepDesc { get; set; }
        public Nullable<int> RouteNumber { get; set; }
        public Nullable<int> Distributor { get; set; }
        public string DistributorName { get; set; }
        public string DeliveryMethod { get; set; }
        public string DeliveryDesc { get; set; }
        public Nullable<int> ContractID { get; set; }
        public string CreditMessage { get; set; }
        public string CreditMessageDesc { get; set; }
        public string SearchType { get; set; }
        public string SearchDesc { get; set; }
        public string BusinessUnit { get; set; }
        public string OrgStructure { get; set; }
        public string BusinessType { get; set; }
        public string Class { get; set; }
        public string ClassDesc { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string AreaCode { get; set; }
        public Nullable<short> ContactActive { get; set; }
        public Nullable<System.DateTime> LastInvDate { get; set; }
        public string SeasonalCustomer { get; set; }
        public string ReportingFamily { get; set; }
        public string ReportingFamilyDesc { get; set; }
        public string LongAddressNumber { get; set; }
        public string CustInternal { get; set; }
        public string AcquisitionCode { get; set; }
        public string Employee { get; set; }
        public Nullable<System.DateTime> LastModifiedByFTP { get; set; }
        public Nullable<short> AuditReadWrite { get; set; }
        public Nullable<int> AuditFlow { get; set; }
        public Nullable<System.DateTime> LastSurveyed { get; set; }
        public Nullable<int> SendInvoiceTo { get; set; }
        public string BusinessLine { get; set; }
        public string CustomerOwnNumber { get; set; }
        public Nullable<int> FSMJDE { get; set; }
        public Nullable<int> ActionCenterJDE { get; set; }
        public string FieldServiceManager { get; set; }
        public string ServiceLevelCode { get; set; }
        public Nullable<System.DateTime> AnniversaryDate { get; set; }
        public string TierDesc { get; set; }
        public Nullable<int> RemainingFreeCalls { get; set; }
        public string Email { get; set; }
        public Nullable<int> CCMJDE { get; set; }
        public Nullable<int> RCCMJDE { get; set; }
        public string CategoryCode { get; set; }
        public string OperatingUnit { get; set; }
        public string Route { get; set; }
        public string Branch { get; set; }
        public string C1099Reporting { get; set; }
        public string Chain { get; set; }
        public string BrewmaticAgentCode { get; set; }
        public string NTR { get; set; }
        public string DelDayOrFOB { get; set; }
        public string RouteCode { get; set; }
        public string ZoneNumber { get; set; }
        public string County { get; set; }
        public string MailingName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> OldContactID { get; set; }
        public string OldSearchType { get; set; }
        public Nullable<int> FBProviderID { get; set; }
        public Nullable<int> NOFBPSPEmails { get; set; }
        public Nullable<System.DateTime> LastAutoEmail { get; set; }
        public Nullable<int> RCCMJDE1 { get; set; }
        public Nullable<int> FSMJDE1 { get; set; }
        public Nullable<int> CCMJDE1 { get; set; }
        public string CustomerRegion { get; set; }
        public string RegionNumber { get; set; }
        public string CustomerBranch { get; set; }
        public string PricingParentID { get; set; }
        public string PricingParentDesc { get; set; }
        public string LastSaleDate { get; set; }
    }
}
