//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class YHERFEquipment
    {
        public string ERFNO { get; set; }
        public int Sno { get; set; }
        public Nullable<int> EquipQuantity { get; set; }
        public string EquipProdNo { get; set; }
        public string EquipType { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public string EquipModelNo { get; set; }
        public string Substitution { get; set; }
        public string EquipDescription { get; set; }
        public Nullable<decimal> Extra { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    }
}
