//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class YHSMEventInvoice
    {
        public Nullable<int> EventID { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> ArrivalDateTime { get; set; }
        public Nullable<System.DateTime> CompletionDateTime { get; set; }
        public Nullable<int> InvoiceUserID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> ModifiedUserid { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> techID { get; set; }
        public string technician { get; set; }
        public int InvoiceKey { get; set; }
    }
}
