//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class YHSMSchedule
    {
        public int Scheduleid { get; set; }
        public int EventID { get; set; }
        public int Techid { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<int> ScheduleUserid { get; set; }
        public Nullable<System.DateTime> ModifiedScheduleDate { get; set; }
        public Nullable<int> ModifiedScheduleUserid { get; set; }
        public int BranchID { get; set; }
    }
}
