//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class YHSMEventSymcall
    {
        public int EventID { get; set; }
        public int AssetKey { get; set; }
        public Nullable<int> CallTypeID { get; set; }
        public string ManufacturerDesc { get; set; }
        public string ProductNo { get; set; }
        public string SerialNo { get; set; }
        public Nullable<int> SolutionId { get; set; }
        public string Temperature { get; set; }
        public string Settings { get; set; }
        public Nullable<int> SystemId { get; set; }
        public Nullable<int> SymptomID { get; set; }
        public string CategoryDesc { get; set; }
        public string Manufacturer { get; set; }
        public string EquipTypeCode { get; set; }
        public string Electricity { get; set; }
        public string Plumbing { get; set; }
        public string NeworReman { get; set; }
        public string Defective { get; set; }
        public string Category { get; set; }
    }
}
