//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zip
    {
        public string ZIP1 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string County { get; set; }
        public string Country { get; set; }
        public string AreaCode { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<short> PreferredCity { get; set; }
        public Nullable<int> TimeZone { get; set; }
        public string DayLightSaving { get; set; }
        public string FIPSState { get; set; }
        public string FIPSCounty { get; set; }
        public string FIPSCity { get; set; }
        public int UniqueID { get; set; }
        public string TimeZoneName { get; set; }
    }
}
