//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneZip
    {
        public int UniqueID { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> ZoneIndex { get; set; }
        public string ZoneName { get; set; }
    }
}
