using System;
using System.Collections.Generic;

namespace DataAccess.Db;

public partial class WorkOrder
{
    public int WorkorderId { get; set; }

    public string? WorkorderCallstatus { get; set; }

    public int? CustomerId { get; set; }

    public string? CustomerName { get; set; }

    public string? CustomerAddress { get; set; }

    public string? CustomerCity { get; set; }

    public string? CustomerState { get; set; }

    public string? CustomerZipCode { get; set; }

    public string? CustomerMainContactName { get; set; }

    public string? CustomerPhone { get; set; }

    public string? CustomerPhoneExtn { get; set; }

    public string? CustomerMainEmail { get; set; }

    public string? CustomerCustomerPreferences { get; set; }

    public int? WorkorderEntryUserid { get; set; }

    public DateTime? WorkorderEntryDate { get; set; }

    public int? WorkorderCloseUserid { get; set; }

    public DateTime? WorkorderCloseDate { get; set; }

    public int? WorkorderModifiedUserid { get; set; }

    public DateTime? WorkorderModifiedDate { get; set; }

    public string? WorkorderErfid { get; set; }

    public short? WorkorderEquipCount { get; set; }

    public int? WorkorderCalltypeid { get; set; }

    public string? WorkorderCalltypeDesc { get; set; }

    public int? WorkorderSpawnEvent { get; set; }

    public int? WorkorderFsm { get; set; }

    public int? WorkorderTimeZone { get; set; }

    public string? WorkorderDaylightSaving { get; set; }

    public string? WorkorderClosureConfirmationNo { get; set; }

    public int? CoverageZone { get; set; }

    public string? TechTeamLead { get; set; }

    public int? ResponsibleTechid { get; set; }

    public string? ResponsibleTechName { get; set; }

    public string? ResponsibleTechPhone { get; set; }

    public int? ResponsibleTechBranch { get; set; }

    public int? SecondaryTechid { get; set; }

    public string? SecondaryTechName { get; set; }

    public string? SecondaryTechPhone { get; set; }

    public int? SecondaryTechBranch { get; set; }

    public string? Fsm { get; set; }

    public string? Rsm { get; set; }

    public string? Tsm { get; set; }

    public string? MarketSegment { get; set; }

    public string? ProgramName { get; set; }

    public string? DistributorName { get; set; }

    public string? ServiceTier { get; set; }

    public string? OtherParts { get; set; }

    public DateTime? DateNeeded { get; set; }

    public string? PurchaseOrder { get; set; }

    public string? PartsShipTo { get; set; }

    public DateTime? AppointmentDate { get; set; }

    public int? OriginalWorkorderid { get; set; }

    public string? CallerName { get; set; }

    public string? OvertimeRequest { get; set; }

    public int? PriorityCode { get; set; }

    public int? ProjectId { get; set; }

    public string? AutoDispatch { get; set; }

    public int? FollowupCallId { get; set; }

    public string? WorkorderContactPhone { get; set; }

    public string? WorkorderContactName { get; set; }

    public int? Fsr { get; set; }

    public bool? PartsRushOrder { get; set; }

    public string? OtherPartsName { get; set; }

    public string? OtherPartsContactName { get; set; }

    public string? OtherPartsAddress1 { get; set; }

    public string? OtherPartsAddress2 { get; set; }

    public string? OtherPartsCity { get; set; }

    public string? OtherPartsState { get; set; }

    public string? OtherPartsZip { get; set; }

    public int? TechTeamLeadId { get; set; }

    public string? EntryUserName { get; set; }

    public string? ClosedUserName { get; set; }

    public string? ModifiedUserName { get; set; }

    public string? Tsmemail { get; set; }

    public string? Tsmphone { get; set; }

    public int? Fsmid { get; set; }

    public decimal? ProjectFlatRate { get; set; }

    public bool? NoServiceRequired { get; set; }

    public string? Fsrname { get; set; }

    public DateTime? HoldDateTime { get; set; }

    public short? EmailSent { get; set; }

    public string? TechType { get; set; }

    public bool? IsRejected { get; set; }

    public string? OtherPartsPhone { get; set; }

    public int? SpawnCounter { get; set; }

    public int? ParentWorkorderid { get; set; }

    public string? CurrentUserName { get; set; }

    public DateTime? WorkOrderOpenedDateTime { get; set; }

    public bool? IsAutoGenerated { get; set; }

    public bool? IsSpecificTechnician { get; set; }

    public string? SpecificTechnician { get; set; }

    public decimal? Estimate { get; set; }

    public decimal? FinalEstimate { get; set; }

    public bool? IsEstimateApproved { get; set; }

    public string? ThirdPartyPo { get; set; }

    public int? EstimateApprovedBy { get; set; }

    public bool? IsAutoDispatched { get; set; }

    public string? HoursOfOperation { get; set; }

    public bool? AutoEmailSent { get; set; }

    public int? OverrideAutoEmail { get; set; }

    public int? HighlightDispatchBoard { get; set; }

    public bool? IsBillable { get; set; }

    public string? TotalUnitPrice { get; set; }

    public bool? ElectronicEmailSent { get; set; }

    public string? CustomerPo { get; set; }

    public int? RescheduleReasonCode { get; set; }

    public string? AuthTransactionId { get; set; }

    public string? FinalTransactionId { get; set; }

    public string? ShippingPriority { get; set; }

    public string? Nte { get; set; }

    public int? Etaupdated { get; set; }

    public string? CallerPhone { get; set; }

    public string? EquipmentBrand { get; set; }

    public string? EquipmentModel { get; set; }

    public string? PaymentTerm { get; set; }

    public virtual ICollection<CcinvoiceDetail> CcinvoiceDetails { get; set; } = new List<CcinvoiceDetail>();

    public virtual ICollection<Fberfexpendable> Fberfexpendables { get; set; } = new List<Fberfexpendable>();

    public virtual ICollection<NonSerialized> NonSerializeds { get; set; } = new List<NonSerialized>();

    public virtual ICollection<NotesHistory> NotesHistories { get; set; } = new List<NotesHistory>();

    public virtual ICollection<PhoneSolveLog> PhoneSolveLogs { get; set; } = new List<PhoneSolveLog>();

    public virtual ICollection<TechSchedule> TechSchedules { get; set; } = new List<TechSchedule>();

    public virtual ICollection<WorkOrderBrand> WorkOrderBrands { get; set; } = new List<WorkOrderBrand>();

    public virtual ICollection<WorkorderDetail> WorkorderDetails { get; set; } = new List<WorkorderDetail>();

    public virtual ICollection<WorkorderEquipmentRequested> WorkorderEquipmentRequesteds { get; set; } = new List<WorkorderEquipmentRequested>();

    public virtual ICollection<WorkorderEquipment> WorkorderEquipments { get; set; } = new List<WorkorderEquipment>();

    public virtual ICollection<WorkorderImage> WorkorderImages { get; set; } = new List<WorkorderImage>();

    public virtual ICollection<WorkorderInstallationSurvey> WorkorderInstallationSurveys { get; set; } = new List<WorkorderInstallationSurvey>();

    public virtual ICollection<WorkorderNonAudit> WorkorderNonAudits { get; set; } = new List<WorkorderNonAudit>();

    public virtual ICollection<WorkorderPart> WorkorderParts { get; set; } = new List<WorkorderPart>();

    public virtual ICollection<WorkorderReasonlog> WorkorderReasonlogs { get; set; } = new List<WorkorderReasonlog>();

    public virtual ICollection<WorkorderSchedule> WorkorderSchedules { get; set; } = new List<WorkorderSchedule>();

    public virtual ICollection<WorkorderStatusLog> WorkorderStatusLogs { get; set; } = new List<WorkorderStatusLog>();
}
