//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerBrothers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomCriteria
    {
        public int UniqueId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryValue { get; set; }
        public string CategoryType { get; set; }
    }
}
