//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerBrothers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMUploads_All
    {
        public int ID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> CustomerJDE { get; set; }
        public Nullable<int> ServiceProviderJDE { get; set; }
        public Nullable<int> EquipCallType { get; set; }
        public string EquipmentType { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> AssetKey { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> ServerEntryDate { get; set; }
        public Nullable<int> TimeZone { get; set; }
        public string DayLightSaving { get; set; }
        public string ZIPCode { get; set; }
        public Nullable<int> SymptomID { get; set; }
        public string EventContact { get; set; }
        public string ContactPhone { get; set; }
        public Nullable<int> PriorityCode { get; set; }
        public Nullable<int> TechID { get; set; }
        public string Description { get; set; }
        public string EquipmentModel { get; set; }
        public string EquipmentLocation { get; set; }
        public string TechEmail { get; set; }
        public string TechName { get; set; }
        public string FamilyAff { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerState { get; set; }
        public string CustomerZipCode { get; set; }
        public string CustomerMainContactName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerPhoneExtn { get; set; }
        public string CustomerMainEmail { get; set; }
    }
}
