//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerBrothers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_BlackBerry_SCFPartsInfo
    {
        public int UniquePartsID { get; set; }
        public Nullable<int> WorkorderID { get; set; }
        public Nullable<int> TechID { get; set; }
        public string EntryNo { get; set; }
        public string ItemNo { get; set; }
        public string VendorNo { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> SKUID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Pid { get; set; }
        public string SKU { get; set; }
        public Nullable<short> Recexists { get; set; }
        public Nullable<int> AssetID { get; set; }
    }
}
