//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerBrothers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_BlackBerry_SCFInvoiceInfo
    {
        public int UniqueInvoiceID { get; set; }
        public Nullable<int> WorkorderID { get; set; }
        public Nullable<int> TechID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> ArrivalDateTime { get; set; }
        public Nullable<System.DateTime> CompletionDateTime { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> InvoiceKey { get; set; }
        public string TechName { get; set; }
        public string SignedBy { get; set; }
        public string Signature { get; set; }
        public Nullable<bool> WaterTested { get; set; }
        public string HardnessRating { get; set; }
        public string CustomerSign { get; set; }
        public string TechnicianSign { get; set; }
        public string StateofEquipment { get; set; }
        public string ServiceDelayReason { get; set; }
        public string TroubleshootSteps { get; set; }
        public string FollowupComments { get; set; }
        public string ReviewedBy { get; set; }
        public string IsUnderWarrenty { get; set; }
        public string WarrentyFor { get; set; }
        public string AdditionalFollowupReq { get; set; }
        public string IsOperational { get; set; }
    }
}
