//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerBrothers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_BlackBerry_SCFAssetInfo
    {
        public int UniqueID { get; set; }
        public Nullable<int> WorkorderID { get; set; }
        public Nullable<int> TechID { get; set; }
        public Nullable<int> ServiceCode { get; set; }
        public Nullable<int> CompletionCode { get; set; }
        public string EquipTypeCode { get; set; }
        public string VendorCode { get; set; }
        public string Model { get; set; }
        public string SerialNo { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<short> CloseCall { get; set; }
        public Nullable<short> EventUpdated { get; set; }
        public Nullable<int> SpawnEventID { get; set; }
        public Nullable<int> AssetKey { get; set; }
        public string ManufacturerDesc { get; set; }
        public string CategoryDesc { get; set; }
        public string ClosureConfirmationNo { get; set; }
        public string Notes { get; set; }
        public Nullable<short> Sent5191Email { get; set; }
        public string TechName { get; set; }
        public string Weight { get; set; }
        public string Ratio { get; set; }
        public Nullable<short> SpawnOrderCreated { get; set; }
        public Nullable<int> SymptomCode { get; set; }
        public Nullable<int> SystemCode { get; set; }
        public string Temperature { get; set; }
        public string ReasonCode { get; set; }
    }
}
