//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerBrothers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_BlackBerry_NSR
    {
        public int UniqueInvoiceID { get; set; }
        public Nullable<int> WorkorderID { get; set; }
        public Nullable<int> TechID { get; set; }
        public string Reasion { get; set; }
        public string Comments { get; set; }
    }
}
