//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerBrothers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkorderDetail
    {
        public Nullable<int> WorkorderID { get; set; }
        public int WorkorderDetailid { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> ArrivalDateTime { get; set; }
        public Nullable<System.DateTime> CompletionDateTime { get; set; }
        public Nullable<int> ResponsibleTechid { get; set; }
        public string ResponsibleTechName { get; set; }
        public Nullable<decimal> Mileage { get; set; }
        public string TravelTime { get; set; }
        public Nullable<int> PhoneSolveid { get; set; }
        public Nullable<int> OriginalWorkorder { get; set; }
        public Nullable<int> SpawnReason { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public byte[] CustomerSignature { get; set; }
        public Nullable<int> EntryUserid { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> ModifiedUserid { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string SpecialClosure { get; set; }
        public Nullable<int> SolutionId { get; set; }
        public string CustomerSignatureDetails { get; set; }
        public Nullable<int> NSRReason { get; set; }
        public Nullable<bool> WaterTested { get; set; }
        public string HardnessRating { get; set; }
        public string TechnicianSignatureDetails { get; set; }
        public string CustomerSignatureBy { get; set; }
    
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
