//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBVixxoService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VixxoEntities : DbContext
    {
        public VixxoEntities()
            : base("name=VixxoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllFBStatu> AllFBStatus { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<TECH_HIERARCHY> TECH_HIERARCHY { get; set; }
        public virtual DbSet<WorkOrder> WorkOrders { get; set; }
        public virtual DbSet<WorkorderDetail> WorkorderDetails { get; set; }
        public virtual DbSet<WorkorderSchedule> WorkorderSchedules { get; set; }
        public virtual DbSet<Zip> Zips { get; set; }
        public virtual DbSet<NotesHistory> NotesHistories { get; set; }
    }
}
