//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBVixxoService
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrder()
        {
            this.WorkorderDetails = new HashSet<WorkorderDetail>();
            this.WorkorderSchedules = new HashSet<WorkorderSchedule>();
            this.NotesHistories = new HashSet<NotesHistory>();
        }
    
        public int WorkorderID { get; set; }
        public string WorkorderCallstatus { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerState { get; set; }
        public string CustomerZipCode { get; set; }
        public string CustomerMainContactName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerPhoneExtn { get; set; }
        public string CustomerMainEmail { get; set; }
        public string CustomerCustomerPreferences { get; set; }
        public Nullable<int> WorkorderEntryUserid { get; set; }
        public Nullable<System.DateTime> WorkorderEntryDate { get; set; }
        public Nullable<int> WorkorderCloseUserid { get; set; }
        public Nullable<System.DateTime> WorkorderCloseDate { get; set; }
        public Nullable<int> WorkorderModifiedUserid { get; set; }
        public Nullable<System.DateTime> WorkorderModifiedDate { get; set; }
        public string WorkorderErfid { get; set; }
        public Nullable<short> WorkorderEquipCount { get; set; }
        public Nullable<int> WorkorderCalltypeid { get; set; }
        public string WorkorderCalltypeDesc { get; set; }
        public Nullable<int> WorkorderSpawnEvent { get; set; }
        public Nullable<int> WorkorderFsm { get; set; }
        public Nullable<int> WorkorderTimeZone { get; set; }
        public string WorkorderDaylightSaving { get; set; }
        public string WorkorderClosureConfirmationNo { get; set; }
        public Nullable<int> CoverageZone { get; set; }
        public string TechTeamLead { get; set; }
        public Nullable<int> ResponsibleTechid { get; set; }
        public string ResponsibleTechName { get; set; }
        public string ResponsibleTechPhone { get; set; }
        public Nullable<int> ResponsibleTechBranch { get; set; }
        public Nullable<int> SecondaryTechid { get; set; }
        public string SecondaryTechName { get; set; }
        public string SecondaryTechPhone { get; set; }
        public Nullable<int> SecondaryTechBranch { get; set; }
        public string Fsm { get; set; }
        public string Rsm { get; set; }
        public string Tsm { get; set; }
        public string MarketSegment { get; set; }
        public string ProgramName { get; set; }
        public string DistributorName { get; set; }
        public string ServiceTier { get; set; }
        public string OtherParts { get; set; }
        public Nullable<System.DateTime> DateNeeded { get; set; }
        public string PurchaseOrder { get; set; }
        public string PartsShipTo { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<int> OriginalWorkorderid { get; set; }
        public string CallerName { get; set; }
        public string OvertimeRequest { get; set; }
        public Nullable<int> PriorityCode { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string AutoDispatch { get; set; }
        public Nullable<int> FollowupCallID { get; set; }
        public string WorkorderContactPhone { get; set; }
        public string WorkorderContactName { get; set; }
        public Nullable<int> FSR { get; set; }
        public Nullable<bool> PartsRushOrder { get; set; }
        public string OtherPartsName { get; set; }
        public string OtherPartsContactName { get; set; }
        public string OtherPartsAddress1 { get; set; }
        public string OtherPartsAddress2 { get; set; }
        public string OtherPartsCity { get; set; }
        public string OtherPartsState { get; set; }
        public string OtherPartsZip { get; set; }
        public Nullable<int> TechTeamLeadID { get; set; }
        public string EntryUserName { get; set; }
        public string ClosedUserName { get; set; }
        public string ModifiedUserName { get; set; }
        public string TSMEmail { get; set; }
        public string TSMPhone { get; set; }
        public Nullable<int> FSMID { get; set; }
        public Nullable<decimal> ProjectFlatRate { get; set; }
        public Nullable<bool> NoServiceRequired { get; set; }
        public string FSRName { get; set; }
        public Nullable<System.DateTime> HoldDateTime { get; set; }
        public Nullable<short> EmailSent { get; set; }
        public string TechType { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public string OtherPartsPhone { get; set; }
        public Nullable<int> SpawnCounter { get; set; }
        public Nullable<int> ParentWorkorderid { get; set; }
        public string CurrentUserName { get; set; }
        public Nullable<System.DateTime> WorkOrderOpenedDateTime { get; set; }
        public Nullable<bool> IsAutoGenerated { get; set; }
        public Nullable<bool> IsSpecificTechnician { get; set; }
        public string SpecificTechnician { get; set; }
        public Nullable<decimal> Estimate { get; set; }
        public Nullable<decimal> FinalEstimate { get; set; }
        public Nullable<bool> IsEstimateApproved { get; set; }
        public string ThirdPartyPO { get; set; }
        public Nullable<int> EstimateApprovedBy { get; set; }
        public Nullable<bool> IsAutoDispatched { get; set; }
        public string HoursOfOperation { get; set; }
        public Nullable<bool> AutoEmailSent { get; set; }
        public Nullable<int> OverrideAutoEmail { get; set; }
        public Nullable<int> HighlightDispatchBoard { get; set; }
        public Nullable<bool> IsBillable { get; set; }
        public string TotalUnitPrice { get; set; }
        public Nullable<bool> ElectronicEmailSent { get; set; }
        public string CustomerPO { get; set; }
        public Nullable<int> RescheduleReasonCode { get; set; }
        public string AuthTransactionId { get; set; }
        public string FinalTransactionId { get; set; }
        public string ShippingPriority { get; set; }
        public string NTE { get; set; }
        public Nullable<int> ETAUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkorderDetail> WorkorderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkorderSchedule> WorkorderSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotesHistory> NotesHistories { get; set; }
    }
}
