//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentDispatchLog
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> WorkorderID { get; set; }
        public string UserName { get; set; }
    }
}
