//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchESM
    {
        public int UniqueId { get; set; }
        public string BranchNo { get; set; }
        public string ESMName { get; set; }
        public string BranchName { get; set; }
    }
}
