//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERFOrderType
    {
        public int OrderTypeId { get; set; }
        public string OrderType { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
