//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimateEscalation
    {
        public int ID { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
