//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBCallReason
    {
        public int SourceID { get; set; }
        public string SourceCode { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateActive { get; set; }
        public Nullable<System.DateTime> DateInactive { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<bool> EmailFSM { get; set; }
        public Nullable<bool> EmailCCM { get; set; }
        public string AdditionalEmail { get; set; }
        public Nullable<int> SalesCall { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<bool> EmailRegional { get; set; }
        public Nullable<bool> EmailSalesManager { get; set; }
        public Nullable<bool> EmailRSR { get; set; }
    }
}
