//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBClosurePart
    {
        public int SkuId { get; set; }
        public string EntryNumber { get; set; }
        public string ItemNo { get; set; }
        public string VendorNo { get; set; }
        public string Description { get; set; }
        public string Supplier { get; set; }
        public string OrderSource { get; set; }
        public string Version { get; set; }
        public Nullable<bool> SkuActive { get; set; }
    }
}
