//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBERFEquipment
    {
        public int ERFEquipmentId { get; set; }
        public string ERFId { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
        public string ModelNo { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ProdNo { get; set; }
        public string EquipmentType { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string TransactionType { get; set; }
        public string Substitution { get; set; }
        public string Extra { get; set; }
        public string Description { get; set; }
        public Nullable<int> ContingentCategoryId { get; set; }
        public Nullable<int> ContingentCategoryTypeId { get; set; }
        public string UsingBranch { get; set; }
        public Nullable<decimal> LaidInCost { get; set; }
        public Nullable<decimal> RentalCost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string InternalOrderType { get; set; }
        public string VendorOrderType { get; set; }
        public string SerialNumber { get; set; }
        public string OrderType { get; set; }
        public string DepositInvoiceNumber { get; set; }
        public Nullable<decimal> DepositAmount { get; set; }
        public string FinalInvoiceNumber { get; set; }
        public Nullable<decimal> InvoiceTotal { get; set; }
    
        public virtual Erf Erf { get; set; }
    }
}
