//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FBReport()
        {
            this.FBUserReports = new HashSet<FBUserReport>();
        }
    
        public int report_id { get; set; }
        public string report_name { get; set; }
        public string report_filename { get; set; }
        public string report_category { get; set; }
        public string DownloadName { get; set; }
        public string DisplayFile { get; set; }
        public string DescriptionFile { get; set; }
        public string DownloadFile { get; set; }
        public Nullable<short> Active { get; set; }
        public string ReportType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FBUserReport> FBUserReports { get; set; }
    }
}
