//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeastMovement
    {
        public Nullable<int> Feastmovementid { get; set; }
        public Nullable<int> WorkorderID { get; set; }
        public string Erfid { get; set; }
        public string FeastmovementState { get; set; }
        public string ShipMethod { get; set; }
        public string ShipCarrier { get; set; }
        public string TrackingNumber { get; set; }
        public string Comments { get; set; }
        public int UniqueID { get; set; }
    }
}
