//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FetcoEntities : DbContext
    {
        public FetcoEntities()
            : base("name=FetcoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgentDispatchLog> AgentDispatchLogs { get; set; }
        public virtual DbSet<AllFBStatu> AllFBStatus { get; set; }
        public virtual DbSet<AMPSList> AMPSLists { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<BillingItem> BillingItems { get; set; }
        public virtual DbSet<BranchESM> BranchESMs { get; set; }
        public virtual DbSet<BrandName> BrandNames { get; set; }
        public virtual DbSet<CallTypeSymptomSolutionMaster> CallTypeSymptomSolutionMasters { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Contact_PMUploadsALL> Contact_PMUploadsALL { get; set; }
        public virtual DbSet<Contingent> Contingents { get; set; }
        public virtual DbSet<ContingentDetail> ContingentDetails { get; set; }
        public virtual DbSet<CustomCriteria> CustomCriterias { get; set; }
        public virtual DbSet<ElectricalPhaseList> ElectricalPhaseLists { get; set; }
        public virtual DbSet<EquipType> EquipTypes { get; set; }
        public virtual DbSet<Erf> Erfs { get; set; }
        public virtual DbSet<ERFBranchDetail> ERFBranchDetails { get; set; }
        public virtual DbSet<ERFOrderType> ERFOrderTypes { get; set; }
        public virtual DbSet<ErfWorkorderLog> ErfWorkorderLogs { get; set; }
        public virtual DbSet<ESMCCMRSMEscalation> ESMCCMRSMEscalations { get; set; }
        public virtual DbSet<ESMDSMRSM> ESMDSMRSMs { get; set; }
        public virtual DbSet<EstimateEscalation> EstimateEscalations { get; set; }
        public virtual DbSet<FBActivityLog> FBActivityLogs { get; set; }
        public virtual DbSet<FBBillableFeed> FBBillableFeeds { get; set; }
        public virtual DbSet<FbBillableSKU> FbBillableSKUs { get; set; }
        public virtual DbSet<FBCallReason> FBCallReasons { get; set; }
        public virtual DbSet<FBCBE> FBCBEs { get; set; }
        public virtual DbSet<FBClosurePart> FBClosureParts { get; set; }
        public virtual DbSet<FBCustomerNote> FBCustomerNotes { get; set; }
        public virtual DbSet<FBCustomerServiceDistribution> FBCustomerServiceDistributions { get; set; }
        public virtual DbSet<FBEquipment> FBEquipments { get; set; }
        public virtual DbSet<FBERFEquipment> FBERFEquipments { get; set; }
        public virtual DbSet<FBERFExpendable> FBERFExpendables { get; set; }
        public virtual DbSet<FBERFPos> FBERFPos { get; set; }
        public virtual DbSet<FBERFTransactionType> FBERFTransactionTypes { get; set; }
        public virtual DbSet<FBExpendable> FBExpendables { get; set; }
        public virtual DbSet<FBFunctionality> FBFunctionalities { get; set; }
        public virtual DbSet<FbPrimaryTechnician> FbPrimaryTechnicians { get; set; }
        public virtual DbSet<FBReport> FBReports { get; set; }
        public virtual DbSet<FBRoleFunction> FBRoleFunctions { get; set; }
        public virtual DbSet<FbRole> FbRoles { get; set; }
        public virtual DbSet<FBSKU> FBSKUs { get; set; }
        public virtual DbSet<FbUserMaster> FbUserMasters { get; set; }
        public virtual DbSet<FBUserReport> FBUserReports { get; set; }
        public virtual DbSet<FbWorkOrderSKU> FbWorkOrderSKUs { get; set; }
        public virtual DbSet<FeastMovement> FeastMovements { get; set; }
        public virtual DbSet<HolidayList> HolidayLists { get; set; }
        public virtual DbSet<IndexCounter> IndexCounters { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<JDEPaymentTerm> JDEPaymentTerms { get; set; }
        public virtual DbSet<NARF_NewAccount> NARF_NewAccount { get; set; }
        public virtual DbSet<NARF_TradeReference> NARF_TradeReference { get; set; }
        public virtual DbSet<NEMANumberList> NEMANumberLists { get; set; }
        public virtual DbSet<NoAutoEmailZipCode> NoAutoEmailZipCodes { get; set; }
        public virtual DbSet<NoAutomaticEmailContract> NoAutomaticEmailContracts { get; set; }
        public virtual DbSet<NonFBCustomer> NonFBCustomers { get; set; }
        public virtual DbSet<NonSerialized> NonSerializeds { get; set; }
        public virtual DbSet<NonServiceworkorder> NonServiceworkorders { get; set; }
        public virtual DbSet<NotesHistory> NotesHistories { get; set; }
        public virtual DbSet<OnCallGroup> OnCallGroups { get; set; }
        public virtual DbSet<PhoneSolveLog> PhoneSolveLogs { get; set; }
        public virtual DbSet<PricingDetail> PricingDetails { get; set; }
        public virtual DbSet<PricingType> PricingTypes { get; set; }
        public virtual DbSet<Privilege> Privileges { get; set; }
        public virtual DbSet<RemovalSurvey> RemovalSurveys { get; set; }
        public virtual DbSet<Sku> Skus { get; set; }
        public virtual DbSet<Solution> Solutions { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<StateTax> StateTaxes { get; set; }
        public virtual DbSet<Symptom> Symptoms { get; set; }
        public virtual DbSet<SystemInfo> SystemInfoes { get; set; }
        public virtual DbSet<TECH_HIERARCHY> TECH_HIERARCHY { get; set; }
        public virtual DbSet<TechOnCall> TechOnCalls { get; set; }
        public virtual DbSet<TechSchedule> TechSchedules { get; set; }
        public virtual DbSet<ThirdpartyConMaintenanceZonerate> ThirdpartyConMaintenanceZonerates { get; set; }
        public virtual DbSet<ThirdPartyContractMaintenance> ThirdPartyContractMaintenances { get; set; }
        public virtual DbSet<TmpInvTransfer> TmpInvTransfers { get; set; }
        public virtual DbSet<TmpinvTransferNonserialized> TmpinvTransferNonserializeds { get; set; }
        public virtual DbSet<TmpinvTransferSerialized> TmpinvTransferSerializeds { get; set; }
        public virtual DbSet<UnKnownCustomerLog> UnKnownCustomerLogs { get; set; }
        public virtual DbSet<UserApplication> UserApplications { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<VoltageList> VoltageLists { get; set; }
        public virtual DbSet<WaterLineList> WaterLineLists { get; set; }
        public virtual DbSet<WorkorderBillingDetail> WorkorderBillingDetails { get; set; }
        public virtual DbSet<WorkOrderBrand> WorkOrderBrands { get; set; }
        public virtual DbSet<WorkorderDetail> WorkorderDetails { get; set; }
        public virtual DbSet<WorkorderEquipment> WorkorderEquipments { get; set; }
        public virtual DbSet<WorkorderEquipmentRequested> WorkorderEquipmentRequesteds { get; set; }
        public virtual DbSet<WorkorderImage> WorkorderImages { get; set; }
        public virtual DbSet<WorkorderInstallationSurvey> WorkorderInstallationSurveys { get; set; }
        public virtual DbSet<WorkorderNonAudit> WorkorderNonAudits { get; set; }
        public virtual DbSet<WorkorderPart> WorkorderParts { get; set; }
        public virtual DbSet<WorkorderReasonlog> WorkorderReasonlogs { get; set; }
        public virtual DbSet<WorkorderSavedSearch> WorkorderSavedSearches { get; set; }
        public virtual DbSet<WorkorderSchedule> WorkorderSchedules { get; set; }
        public virtual DbSet<WorkorderServiceClaim> WorkorderServiceClaims { get; set; }
        public virtual DbSet<WorkorderStatusLog> WorkorderStatusLogs { get; set; }
        public virtual DbSet<WorkorderType> WorkorderTypes { get; set; }
        public virtual DbSet<ZonePriority> ZonePriorities { get; set; }
        public virtual DbSet<FbPrimaryTechnicians1> FbPrimaryTechnicians1 { get; set; }
        public virtual DbSet<TECH_HIERARCHY_BACKUP> TECH_HIERARCHY_BACKUP { get; set; }
        public virtual DbSet<TMP_SerialNOReport> TMP_SerialNOReport { get; set; }
        public virtual DbSet<YHCompassSurvey> YHCompassSurveys { get; set; }
        public virtual DbSet<YHContact> YHContacts { get; set; }
        public virtual DbSet<YHContact_PMUploadsALL> YHContact_PMUploadsALL { get; set; }
        public virtual DbSet<YHERFEquipment> YHERFEquipments { get; set; }
        public virtual DbSet<YHERFExpendable> YHERFExpendables { get; set; }
        public virtual DbSet<YHEventBrand> YHEventBrands { get; set; }
        public virtual DbSet<YHEventNote> YHEventNotes { get; set; }
        public virtual DbSet<YHSMEvent> YHSMEvents { get; set; }
        public virtual DbSet<YHSMEventInvoice> YHSMEventInvoices { get; set; }
        public virtual DbSet<YHSMEventSymcall> YHSMEventSymcalls { get; set; }
        public virtual DbSet<YHSMSchedule> YHSMSchedules { get; set; }
        public virtual DbSet<Zip> Zips { get; set; }
        public virtual DbSet<ZoneZip> ZoneZips { get; set; }
        public virtual DbSet<v_AllPMandServiceEventsWithUniqueSerial> v_AllPMandServiceEventsWithUniqueSerial { get; set; }
        public virtual DbSet<v_Contact> v_Contact { get; set; }
        public virtual DbSet<v_ContactServiceHistory> v_ContactServiceHistory { get; set; }
        public virtual DbSet<V_EquipmentCount> V_EquipmentCount { get; set; }
        public virtual DbSet<V_LastOneyearDispatches> V_LastOneyearDispatches { get; set; }
        public virtual DbSet<V_LastOneyearInvoices> V_LastOneyearInvoices { get; set; }
        public virtual DbSet<V_OpenCallTime> V_OpenCallTime { get; set; }
        public virtual DbSet<V_OriginalCallDetails> V_OriginalCallDetails { get; set; }
        public virtual DbSet<V_RepeatedPMandServiceEventDetails> V_RepeatedPMandServiceEventDetails { get; set; }
        public virtual DbSet<V_RepeatedPMandServiceEvents> V_RepeatedPMandServiceEvents { get; set; }
        public virtual DbSet<V_RepeatServiceRepair> V_RepeatServiceRepair { get; set; }
        public virtual DbSet<V_RepeatServiceRepairDetails> V_RepeatServiceRepairDetails { get; set; }
        public virtual DbSet<VW_FBRoleFunction> VW_FBRoleFunction { get; set; }
        public virtual DbSet<VW_tech_Hierarchy> VW_tech_Hierarchy { get; set; }
        public virtual DbSet<FetcoCustomer> FetcoCustomers { get; set; }
        public virtual DbSet<WorkOrder> WorkOrders { get; set; }
    }
}
