//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class NARF_NewAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NARF_NewAccount()
        {
            this.NARF_TradeReference = new HashSet<NARF_TradeReference>();
        }
    
        public int ApplicationId { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string DBAName { get; set; }
        public string BilllingAddress { get; set; }
        public string BilllingState { get; set; }
        public string BilllingCity { get; set; }
        public string BilllingZip { get; set; }
        public string DeliveryAddress { get; set; }
        public string DeliveryState { get; set; }
        public string DeliveryCity { get; set; }
        public string DeliveryZip { get; set; }
        public string CompanyType { get; set; }
        public string PrincipalOfficer { get; set; }
        public string PrincipalOfficerTitle { get; set; }
        public string NatureOfBusiness { get; set; }
        public string EstablishedYear { get; set; }
        public string StateIncorporated { get; set; }
        public string FederalTaxID { get; set; }
        public string ResaleCertificateNumber { get; set; }
        public Nullable<bool> TaxExempt { get; set; }
        public Nullable<bool> PORequired { get; set; }
        public Nullable<bool> AlreadyHasFBAccount { get; set; }
        public string FBAccount { get; set; }
        public string AccountPayableContact { get; set; }
        public string AccountPayableTitle { get; set; }
        public string AccountPayablePhone { get; set; }
        public string AccountPayableEmail { get; set; }
        public Nullable<decimal> CreditRequested { get; set; }
        public int CreatedUserID { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedUserID { get; set; }
        public string ModifiedUserName { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NARF_TradeReference> NARF_TradeReference { get; set; }
    }
}
