//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonServiceworkorder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NonServiceworkorder()
        {
            this.NotesHistories = new HashSet<NotesHistory>();
        }
    
        public int NonServiceID { get; set; }
        public int WorkOrderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CallReason { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerState { get; set; }
        public string CustomerZipCode { get; set; }
        public Nullable<bool> IsAutoDispatched { get; set; }
        public string CallerName { get; set; }
        public string CallBack { get; set; }
        public Nullable<bool> IsUnknownWorkOrder { get; set; }
        public string NonServiceEventStatus { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string EmailSentTo { get; set; }
        public string MainContactName { get; set; }
        public string PhoneNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotesHistory> NotesHistories { get; set; }
    }
}
