//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneSolveLog
    {
        public int PhoneSolveLogId { get; set; }
        public int WorkorderId { get; set; }
        public int PhoneSolveId { get; set; }
        public Nullable<int> TechId { get; set; }
        public System.DateTime AttemptedDate { get; set; }
    
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
