//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricingDetail
    {
        public int Id { get; set; }
        public string PricingEntityId { get; set; }
        public string PricingEntityName { get; set; }
        public Nullable<decimal> HourlyTravlRate { get; set; }
        public Nullable<decimal> HourlyLablrRate { get; set; }
        public Nullable<decimal> MilageRate { get; set; }
        public Nullable<decimal> AfterHoursTravelRate { get; set; }
        public Nullable<decimal> AfterHoursLaborRate { get; set; }
        public Nullable<decimal> PartsDiscount { get; set; }
        public Nullable<bool> AfterHoursRatesApply { get; set; }
        public Nullable<decimal> AdditionalFee { get; set; }
        public Nullable<int> PricingTypeId { get; set; }
        public Nullable<bool> Approved3rdPartyUse { get; set; }
    
        public virtual PricingType PricingType { get; set; }
    }
}
