//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateTax
    {
        public int Id { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string TaxRegionName { get; set; }
        public Nullable<double> EstimatedCombinedRate { get; set; }
        public Nullable<double> StateRate { get; set; }
        public Nullable<double> EstimatedCountyRate { get; set; }
        public Nullable<double> EstimatedCityRate { get; set; }
        public Nullable<double> EstimatedSpecialRate { get; set; }
    }
}
