//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symptom
    {
        public int SymptomID { get; set; }
        public string Description { get; set; }
        public Nullable<short> Sequence { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> ColUpdated { get; set; }
    }
}
