//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThirdPartyContractMaintenance
    {
        public int ContractMaintenanceid { get; set; }
        public int Techid { get; set; }
        public Nullable<decimal> PartsUpCharge { get; set; }
        public Nullable<decimal> LaborHourlyRate { get; set; }
        public Nullable<decimal> LaborOvertimeRate { get; set; }
        public Nullable<bool> MinOneHourFlag { get; set; }
        public Nullable<bool> RatePerPalletFlag { get; set; }
        public Nullable<decimal> RatePerPallet { get; set; }
        public Nullable<bool> TravelRatePerMileFlag { get; set; }
        public Nullable<decimal> TravelRatePerMile { get; set; }
        public Nullable<bool> TravelAllowRoundTripFlag { get; set; }
        public Nullable<bool> TravelMinOneHour { get; set; }
        public Nullable<bool> TravelHourlyRateFlag { get; set; }
        public Nullable<decimal> TravelHourlyRate { get; set; }
        public Nullable<bool> TravelOverTimeRateFlag { get; set; }
        public Nullable<decimal> TravelOvertimeRate { get; set; }
        public Nullable<bool> TravelZoneRateFlag { get; set; }
    }
}
