//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int Techid { get; set; }
        public Nullable<int> Branchid { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public Nullable<System.DateTime> LastAcceptDate { get; set; }
        public string TechType { get; set; }
        public string UsrPassword { get; set; }
        public string UserName { get; set; }
        public string ApiKey { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string TokenKey { get; set; }
        public string UserID { get; set; }
        public Nullable<int> UserActive { get; set; }
        public string DispatchEmails { get; set; }
        public Nullable<bool> TechnicianAccount { get; set; }
        public Nullable<bool> InvoicingAccount { get; set; }
        public bool IsInvoice { get; set; }
    }
}
