//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AllPMandServiceEventsWithUniqueSerial
    {
        public int WorkorderID { get; set; }
        public string WorkorderCallstatus { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> WorkorderEntryDate { get; set; }
        public Nullable<System.DateTime> WorkorderCloseDate { get; set; }
        public Nullable<int> CallTypeid { get; set; }
        public string Category { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> Symptomid { get; set; }
    }
}
