//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ContactServiceHistory
    {
        public int WorkorderID { get; set; }
        public string WorkorderCallstatus { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Category { get; set; }
        public string Model { get; set; }
        public string Manufacturer { get; set; }
        public string Location { get; set; }
        public string SerialNumber { get; set; }
        public string CallTypeDesc { get; set; }
        public string SymptomDesc { get; set; }
        public int SymptomID { get; set; }
        public int CallTypeID { get; set; }
        public Nullable<System.DateTime> WorkorderEntryDate { get; set; }
        public Nullable<int> Solutionid { get; set; }
        public Nullable<int> Systemid { get; set; }
        public string Description { get; set; }
        public int Assetid { get; set; }
    }
}
