//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LastOneyearInvoices
    {
        public int WorkorderID { get; set; }
        public string WorkorderCallstatus { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> WorkorderEntryDate { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> ArrivalDateTime { get; set; }
        public Nullable<System.DateTime> CompletionDateTime { get; set; }
        public Nullable<int> ResponsibleTechid { get; set; }
        public string ResponsibleTechName { get; set; }
    }
}
