//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OpenCallTime
    {
        public int WorkorderID { get; set; }
        public Nullable<System.DateTime> WorkorderEntryDate { get; set; }
        public Nullable<int> Techid { get; set; }
        public string DispatchCompany { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<int> ScheduleUserid { get; set; }
        public string ElapsedTime { get; set; }
        public int ElapsedTimeInMins { get; set; }
        public string WorkorderCallstatus { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public int ContactID { get; set; }
        public string CustomerRegion { get; set; }
        public string CustomerBranchNo { get; set; }
        public string RegionNumber { get; set; }
        public string CustomerBranch { get; set; }
        public string FamilyAff { get; set; }
        public string SearchType { get; set; }
        public string SearchDesc { get; set; }
        public string AssignedStatus { get; set; }
    }
}
