//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RepeatedPMandServiceEvents
    {
        public int WorkorderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> WorkorderEntryDate { get; set; }
        public Nullable<System.DateTime> WorkorderCloseDate { get; set; }
        public Nullable<int> CallTypeid { get; set; }
        public string Category { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> Symptomid { get; set; }
        public int RepeatedEventId { get; set; }
        public Nullable<System.DateTime> RepeatedEntryDate { get; set; }
        public Nullable<System.DateTime> RepeatedCloseDate { get; set; }
        public Nullable<int> RepeatedCallTypeID { get; set; }
        public string RepeatedCategory { get; set; }
        public string RepeatedManufacturer { get; set; }
        public string RepeatedModel { get; set; }
        public string RepeatSerialNumber { get; set; }
        public Nullable<int> RepeatSymptomid { get; set; }
    }
}
