//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_tech_Hierarchy
    {
        public string RSMName { get; set; }
        public string RSMPhone { get; set; }
        public string ESMName { get; set; }
        public string ESMPhone { get; set; }
        public string DSMName { get; set; }
        public string DSMPhone { get; set; }
        public string Branch { get; set; }
        public string RegionName { get; set; }
        public Nullable<int> RSMID { get; set; }
        public Nullable<int> ESMID { get; set; }
        public Nullable<int> DSMID { get; set; }
        public string PreferredProvider { get; set; }
        public string ProviderPhone { get; set; }
        public string PricingParent { get; set; }
        public int TechID { get; set; }
        public string TechZIP { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string TechType { get; set; }
        public string TechTypeDesc { get; set; }
        public string TechEmail { get; set; }
        public string RegionNumber { get; set; }
        public string BranchNumber { get; set; }
        public string BranchName { get; set; }
        public string AreaCode { get; set; }
        public string SearchType { get; set; }
    }
}
