//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterLineList
    {
        public int WaterLineID { get; set; }
        public string WaterLine { get; set; }
        public Nullable<double> Active { get; set; }
        public Nullable<double> Sequence { get; set; }
    }
}
