//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkorderPart
    {
        public int PartsIssueid { get; set; }
        public Nullable<int> WorkorderID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Manufacturer { get; set; }
        public string Sku { get; set; }
        public string Description { get; set; }
        public Nullable<int> Erfid { get; set; }
        public string ProdNo { get; set; }
        public string ModelNo { get; set; }
        public Nullable<decimal> StandardCost { get; set; }
        public Nullable<decimal> TPSPCost { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> AssetID { get; set; }
        public Nullable<bool> NonSerializedIssue { get; set; }
    
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
