//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkorderBillingDetail
    {
        public int BillingId { get; set; }
        public Nullable<int> WorkorderId { get; set; }
        public string BillingCode { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Duration { get; set; }
    }
}
