//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkorderStatusLog
    {
        public int WorkorderStatusLogID { get; set; }
        public int WorkorderID { get; set; }
        public string StatusFrom { get; set; }
        public string StatusTo { get; set; }
        public System.DateTime StausChangeDate { get; set; }
    
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
