//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkorderNonAudit
    {
        public int NonAuditid { get; set; }
        public Nullable<int> WorkorderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> Techid { get; set; }
        public string Category { get; set; }
        public string Equipment { get; set; }
        public string Model { get; set; }
        public string Location { get; set; }
        public string SerialNumber { get; set; }
    
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
