//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkorderImage
    {
        public int WorkorderImageid { get; set; }
        public Nullable<int> WorkorderDetailid { get; set; }
        public Nullable<int> WorkorderID { get; set; }
        public byte[] WorkorderPicture { get; set; }
        public string WorkorderImagePath { get; set; }
        public Nullable<int> AssetID { get; set; }
    
        public virtual WorkorderEquipment WorkorderEquipment { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
