//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkorderEquipmentRequested
    {
        public int Assetid { get; set; }
        public Nullable<int> CallTypeid { get; set; }
        public string Category { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Location { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> Solutionid { get; set; }
        public string Temperature { get; set; }
        public string Settings { get; set; }
        public Nullable<int> Systemid { get; set; }
        public Nullable<int> Symptomid { get; set; }
        public Nullable<bool> QualityIssue { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string WorkDescription { get; set; }
        public Nullable<int> WorkorderID { get; set; }
        public string WorkPerformedCounter { get; set; }
        public Nullable<bool> NoPartsNeeded { get; set; }
        public string CatalogID { get; set; }
        public Nullable<int> FeastMovementid { get; set; }
        public Nullable<bool> IsSlNumberImageExist { get; set; }
        public Nullable<int> EquipmentId { get; set; }
        public string Weight { get; set; }
        public string Ratio { get; set; }
    
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
