//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class YHERFExpendable
    {
        public string ERFNO { get; set; }
        public Nullable<int> ExpQuantity { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public string ExpProdNo { get; set; }
        public string ExpModelNo { get; set; }
        public string EXpDescription { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Extra { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public int Sno { get; set; }
    }
}
