//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class YHEventNote
    {
        public int UniqueID { get; set; }
        public Nullable<int> EvenTID { get; set; }
        public Nullable<int> USerID { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public string USerName { get; set; }
        public string Notes { get; set; }
        public Nullable<int> AutomaticNotes { get; set; }
        public int EventNotesID { get; set; }
    }
}
