//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetcoCall
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZonePriority
    {
        public int ZoneIndex { get; set; }
        public string ZoneName { get; set; }
        public Nullable<int> ResponsibletechID { get; set; }
        public string ResponsibleTechName { get; set; }
        public string ResponsibleTechPhone { get; set; }
        public Nullable<int> TechTeamLead { get; set; }
        public Nullable<int> ResponsibleTechBranch { get; set; }
        public Nullable<int> SecondaryTechID { get; set; }
        public string SecondaryTechName { get; set; }
        public string SecondaryTechPhone { get; set; }
        public Nullable<int> SecondaryTechBranch { get; set; }
        public Nullable<int> Fsm { get; set; }
        public Nullable<int> Rsm { get; set; }
        public Nullable<int> Tsm { get; set; }
        public string TechTeamLeadName { get; set; }
        public string ResponsibleTechBranchName { get; set; }
        public string SecondaryTechBranchName { get; set; }
        public string RSMName { get; set; }
        public string FSMName { get; set; }
        public Nullable<int> PhoneSolveTechID { get; set; }
        public string PhoneSolveTechName { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string Coordinates { get; set; }
        public Nullable<int> OnCallGroupID { get; set; }
        public Nullable<int> OnCallPrimarytechID { get; set; }
        public Nullable<int> OnCallBackupTechID { get; set; }
    }
}
